---
name: LightningTP
version: 1.0.0
main: pixelwhiz\lightningtp\Main
api: 5.0.0
src-namespace-prefix: pixelwhiz\lightningtp
permissions:
  lightningtp.tp:
    description: "allow all"
    default: op
...
